trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  name : default 
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - powershell: echo Build First Job
      - powershell: echo $(Pipeline.Workspace)
      - powershell: echo $(Build.BuildNumber)
      - powershell: echo $(Build.BuildId)
      - powershell: echo $(Build.SourceBranchName)
      - powershell: echo $(Build.SourcesDirectory)
      - powershell: echo $(System.DefaultWorkingDirectory)
      - powershell: ls -r  $(System.DefaultWorkingDirectory)
      - powershell: echo $(Build.ArtifactStagingDirectory)