trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  name : default
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - powershell : echo Build First Job
    - job: SecondJob
      steps:
      - powershell: echo Build Second Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
    - job: DevFist
      steps:
      - powershell: echo Dev First Job
    - job: DevSeccond
      steps:
      - powershell: echo Dev Second Job
- stage: QADeploy
  dependsOn: Build
  jobs:
    - job: QAJob
      steps:
      - powershell: echo QA First Job
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
    - job: ProductionsJob
      steps:
      - powershell: echo Production First Job