trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  name : default 
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - powershell: ls -R $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: |
            **/*.yml
            **/*.java
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - powershell: ls -R $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'