trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  name :  default 
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - powershell: echo Build First Job
    - job: SecondJob
      steps:
      - powershell: echo Build Second Job
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
    - job: DevFist
      steps:
      - powershell: echo $(environment)DeployJob
    - job: DevSeccond
      steps:
      - powershell: echo Dev Second Job
- stage: QADeploy
  variables:
     environment: 
  dependsOn: Build
  jobs:
    - job: QAJob
      steps:
      - powershell: echo $(environment)QADeploy
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
    - job: ProductionsJob
      steps:
      - powershell: echo $(environment)ProdDeploy